-- veilproof-server schema. Stores only leaf commitments (hashes issuers
-- compute off-chain) and server-side bookkeeping — never raw PII or holder
-- secrets. The veilproof-registry contract is the source of truth for
-- on-chain state; these tables are a convenience cache.

CREATE TABLE IF NOT EXISTS issuers (
    name        TEXT PRIMARY KEY,
    -- The last root this issuer published via /publish, as 64 lowercase hex
    -- chars (32 big-endian bytes). NULL until the first publish.
    published_root TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS leaves (
    issuer_name TEXT NOT NULL REFERENCES issuers(name) ON DELETE CASCADE,
    -- Position in the tree, assigned in insertion order.
    position    INTEGER NOT NULL,
    -- Leaf commitment: 64 lowercase hex chars. A hash, never raw PII.
    commitment  TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (issuer_name, position)
);

-- Server-side bookkeeping only. A row here means "a proof was generated by
-- this server for this nullifier", NOT that it was used on-chain — the
-- contract is authoritative for on-chain nullifier state. Populating this
-- from chain events is future work.
CREATE TABLE IF NOT EXISTS generated_nullifiers (
    issuer_name TEXT NOT NULL REFERENCES issuers(name) ON DELETE CASCADE,
    nullifier   TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (issuer_name, nullifier)
);
